# Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d4n87pruibrs7396uctg-a.singapore-postgres.render.com/moneymanager_9syb
spring.datasource.username=moneymanager_9syb_user
spring.datasource.password=gBigOY715N8UGg0Kxc9XlRZ51WTrLRw5


