# Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d4n87pruibrs7396uctg-a.singapore-postgres.render.com/moneymanager_9syb
spring.datasource.username=moneymanager_9syb_user
spring.datasource.password=gBigOY715N8UGg0Kxc9XlRZ51WTrLRw5
<<<<<<< HEAD



=======
>>>>>>> 467b2bd8c879f63c083ca113a86c6eea39c3928d
