# Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d3hn50p5pdvs73fdemk0-a.singapore-postgres.render.com/moneymanager_i74t
spring.datasource.username=moneymanager_i74t_user
spring.datasource.password=7TWluy6N5ZaKJIOJd7F2z0xmC7rs9MMI
