# Postgresql Configuration
spring.datasource.url=jdbc:postgresql://dpg-d3egolqli9vc739mma4g-a.singapore-postgres.render.com/moneymanager_7z4u
spring.datasource.username=moneymanager_7z4u_user
spring.datasource.password=wPiUH3gx9NTqN0l6dhEMdUK0rpcw2TS7